In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default = "plotly_white"

In [ ]:
df=pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [32]:
len(df)

10000

1.Find the total number of customers in each country.

In [ ]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

2. Find the average credit score of customers based on gender.

In [ ]:
df.groupby('Gender')['CreditScore'].mean()
#df.groupby('Gender')['CreditScore'].sum()

Gender
Female    650.831389
Male      650.276892
Name: CreditScore, dtype: float64

3. Find the total number of customers who exited and customers who stayed.

In [ ]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

4. Find the average account balance in each country.

In [ ]:
df.groupby('Geography')['Balance'].mean()

Geography
France      62092.636516
Germany    119730.116134
Spain       61818.147763
Name: Balance, dtype: float64

5. Find which age has the highest number of customers who exited the bank.

In [22]:
chhod_gye=df.groupby('Age')['Exited'].sum().sort_values(ascending=False)
chhod_gye.head()

Age
46    91
40    89
43    88
45    87
48    80
Name: Exited, dtype: int64

6. Find the average estimated salary of active and inactive members.

In [ ]:
activ_log=df.groupby('IsActiveMember')['EstimatedSalary'].mean()
activ_log.head()

IsActiveMember
0    100767.203854
1     99452.965894
Name: EstimatedSalary, dtype: float64

7. Find the churn count based on the number of products customers are using.

In [ ]:
pro_cus=df.groupby('NumOfProducts')['Exited'].sum()
pro_cus.head()

NumOfProducts
1    1409
2     348
3     220
4      60
Name: Exited, dtype: int64

8. Create a separate DataFrame containing country and region information, merge it with the
main dataset using pd.merge(), and then find the average balance and average estimated
salary by region.

In [30]:
info=df.groupby('Geography')['Age'].mean().reset_index()
info

  Geography        Age
0    France  38.511767
1   Germany  39.771622
2     Spain  38.890997

In [27]:
mar=pd.merge(df,info,on='Geography')
mar

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age_x,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Age_y
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,38.511767
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,38.890997
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,38.511767
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,38.511767
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,38.890997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0,38.511767
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0,38.511767
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1,38.511767
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1,39.771622
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0,38.511767

In [28]:
df.groupby('Geography')['EstimatedSalary'].mean()

Geography
France      99899.180814
Germany    101113.435102
Spain       99440.572281
Name: EstimatedSalary, dtype: float64