In [46]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

In [47]:
df=pd.read_csv('/content/tips.csv')
df.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [48]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [49]:
x_train,x_test,y_train,y_test=train_test_split(df.drop('tip',axis=1),df['tip'],test_size=0.3,random_state=2)

In [50]:
si=SimpleImputer(strategy='mean')
x_train_totalbill=si.fit_transform(x_train[['total_bill']])
x_test_totalbill=si.transform(x_test[['total_bill']])
x_test_totalbill.shape

(74, 1)

In [51]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [52]:
oe=OrdinalEncoder(categories=[['Thur','Fri','Sat','Sun']])
x_train_day=oe.fit_transform(x_train[['day']])
x_test_day=oe.transform(x_test[['day']])
x_test_day.shape

(74, 1)

In [53]:
ohe=OneHotEncoder(sparse_output=False,drop='first')
x_train_smoker=ohe.fit_transform(x_train[['smoker','time']])
x_test_smoker=ohe.transform(x_test[['smoker','time']])
x_test_smoker.shape

(74, 2)

In [54]:
si=SimpleImputer(strategy='mean')
x_train_size=si.fit_transform(x_train[['size']])
x_test_size=si.transform(x_test[['size']])
x_test_size.shape

(74, 1)

In [55]:
x_train_transformed=np.concatenate((x_train_totalbill,x_train_day,x_train_smoker,x_train_size),axis=1)
x_train_transformed.shape

(170, 5)

In [56]:
transform=ColumnTransformer(transform=[
    ('t1',SimpleImputer,['total_bill']),
    ('t2',OrdinalEncoder(categories=[['Thur','Fri','Sat','Sun']]),['day']),
    ('t3',OneHotEncoder(sparse_output=False,drop='first'),['smoker','time']),
    ('t4',SimpleImputer(strategy='mean'),['size'])
],remainder='passthrough')

TypeError: ColumnTransformer.__init__() got an unexpected keyword argument 'transform'

In [ ]:
df['day'].value_counts()

In [ ]:
transformer=ColumnTransformer(transformers=[
    ('t1',SimpleImputer,['total_bill']),
    ('t2',OrdinalEncoder(categories=[['Thur','Fri','Sat','Sun']]),['day']),
    ('t3',OneHotEncoder(sparse_output=False,drop='first'),['smoker','time']),
    ('t4',SimpleImputer(strategy='mean'),['size'])],remainder='passthrough')

In [ ]:
transformer.fit_transform(x_train).shape